### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by cooperate** [fungus1487/xbmc-hockey-streams#14]
18:36:16 T:3308   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 11001] getaddrinfo failed>
                                            Traceback (most recent call last):
                                              File "C:\Users[username]\AppData\Roaming\Kodi\addons\plugin.video.xbmc-hockey-streams-gotham\default.py", line 1300, in <module>
                                                session = streams.login(username, password)
                                              File "C:\Users[username]\AppData\Roaming\Kodi\addons\plugin.video.xbmc-hockey-streams-gotham\streams.py", line 230, in login
                                                response = urllib2.urlopen(request, data)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 404, in open
                                                response = self._open(req, data)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 422, in _open
                                                '_open', req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1222, in https_open
                                                return self.do_open(httplib.HTTPSConnection, req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1184, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 11001] getaddrinfo failed>
                                            -->End of Python script error report<--
18:36:16 T:7120   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.xbmc-hockey-streams-gotham/
18:36:16 T:7120   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.xbmc-hockey-streams-gotham/) failed

**Comment by Swedemon** [comment]
If you didn't notice hockeystreams.com and ballstreams.com died yesterday.  Disappeared without a word.

**Comment by cooperate** [comment]
i didn't even think to check the website. ouch! doesn't look like its coming back
